server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: cinema-service
  datasource:
    url: jdbc:mysql://120.92.164.231:3306/maoyan_dubbo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    filters: log4j,wall,mergeStat

# springboot 监控 Actuator, 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
mybatis-plus:
  mapper-locations: classpath*:com/ashen/ccfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

